language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame

script:
    - echo $PYTHONPATH
    - python3 -m unittest

virtualenv:
    system_site_packages: true

# http://5minutes.youkidea.com/howto-deploy-python-package-on-pypi-with-github-and-travis.html
# deploy:
#     provider: pypi
#     user: florimondmanca
#     password:
#         secure: 211242Coaster96
#     on:
#         tags: true
#         branch: master
