language: python

python:
    - "3.4"

env:
  global:
    - PYTHONPATH="/home/travis/build/florimondmanca/pygame-assets"
    - PIP_USE_MIRRORS=true

before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame

before_script:
    - cd pygame_assets
    - python -c "import os; os.environ['SDL_VIDEODRIVER'] = 'dummy'"

script:
    - python3 -m unittest

after_script:
    - cd ..

virtualenv:
    system_site_packages: true
